from minhas_notas_musicais import *

print("Escalas maiores:")
print(Escala(A))
print(Escala(As))
print(Escala(Ab))
print(Escala.intervalos())
print()

print("Escalas menores:")
print(Escala(A, 'menor'))
print(Escala(As, 'menor'))
print(Escala(Ab, 'menor'))
print(Escala.intervalos('menor'))
print()

print("Escalas menores harmônicas:")
print(Escala(A, 'menor-harmonica'))
print(Escala(As, 'menor-harmonica'))
print(Escala(Ab, 'menor-harmonica'))
print(Escala.intervalos('menor-harmonica'))
print()

print("Escalas menores melódicas:")
print(Escala(A, 'menor-melodica'))
print(Escala(As, 'menor-melodica'))
print(Escala(Ab, 'menor-melodica'))
print(Escala.intervalos('menor-melodica'))
print()

print("Progressões:")
prog = Progresssao.parse('G7+ D9 Em7(13) Csus2')
print(prog)
print(prog.semitom())
print(prog.tom())
print(prog.transpor('E'))
print(prog.transpor('B'))
print(prog.transpor('C#'))
print(prog.transpor('Bb'))
